# -*- coding: utf-8 -*-
"""python end project new.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CL-zzKAV2M-7ujs06IP0deBNZC7lV1p_
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

path='/content/drive/MyDrive/myexcel - myexcel.csv.csv'

df=pd.read_csv(path)
path
df

df['Height']=np.random.randint(150,181,size=len(df))

df

Team_distribution=df['Team'].value_counts()
Team_distribution

Total_employees=len(df)
Total_employees

Team_percentage=(Team_distribution/Total_employees)*100

Team_percentage

df['Position'].value_counts()

positions=df[['Position','Name']]
positions

df['Age'].mode()

df['Age'].mean()

df['Salary'].describe()

df['Salary'].mean()

#we have 11 missing values in salary column.
#replace it with mean of salary.
df['Salary']=df['Salary'].fillna(4833969)

df.isnull().sum()

df['College'].describe()

#we have 84 missing values in college column .replace it with most frequent value.
df['College']=df['College'].fillna('Kentucky')

df.isnull().sum()

team_salary = df.groupby('Team')['Salary'].sum().reset_index()
team_salary

max_salary_team = team_salary.loc[team_salary['Salary'].idxmax()]
max_salary_team

df

sns.lineplot(data=df,x='Age',y='Salary',marker='o',linestyle='--')
plt.title('AGE VS SALARY',fontsize=20,color='red')
plt.xlabel('Age',fontsize=15)
plt.ylabel('Salary',fontsize=15)
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.show()

import seaborn as sns
sns.barplot(data=df,x='Salary',y='Team',orient='h',color='c')
plt.title('SALARY VS TEAM',fontsize=20,color='red')
plt.xlabel('Team',fontsize=15,color='k')
plt.ylabel('Salary',fontsize=15,color='k')
plt.xticks(fontsize=15,color='k')
plt.yticks(fontsize=8,color='k')
plt.show()

plt.hist(data=df,x='Salary',bins=10,color='m',edgecolor='k',alpha=0.7,histtype='bar',rwidth=0.8,label='Salary')
plt.title('SALARY DISTRIBUTION',fontsize=20,color='r',fontweight='bold')
plt.xlabel('Salary',fontsize=15,color='k')
plt.ylabel('Frequency',fontsize=15,color='k')
plt.legend()
plt.show()

sns.boxplot(data=df,x='Salary',y='Position',orient='h',color='c',width=0.5,saturation=1,linewidth=1)
plt.title('SALARY VS POSITION',fontsize=20,color='r')
plt.xlabel('Salary',fontsize=15,color='k')
plt.ylabel('Position',fontsize=15,color='k')
plt.show()

sns.boxplot(data=df,x='Height',y='Position',orient='h',color='g',width=0.5,saturation=1,linewidth=1)
plt.title('HEIGHT VS POSITION',fontsize=20,color='r')
plt.xlabel('Height',fontsize=15,color='k')
plt.ylabel('Position',fontsize=15,color='k')
plt.show()

sns.lmplot(data=df,x='Salary',y='Age')
plt.title('SALARY VS AGE',fontsize=20,color='r')
plt.xlabel('Salary',fontsize=15,color='k')
plt.ylabel('Age',fontsize=15,color='k')
plt.show()

average_salary=df['Salary'].mean()
average_salary

sns.barplot(data=df,x='Position',y='Salary',color='g')
plt.title('POSITION VS SALARY',fontsize=20,color='r')
plt.xlabel('Position',fontsize=15,color='k')
plt.ylabel('Salary',fontsize=15,color='k')
plt.show()

sns.barplot(data=df,x='Height',y='Salary',color='purple',edgecolor='k')
plt.title('HEIGHT VS SALARY',fontsize=20,color='r')
plt.xlabel('Height',fontsize=15,color='k')
plt.ylabel('Salary',fontsize=15,color='k')
plt.xticks(fontsize=5,color='r')
plt.yticks(fontsize=5,color='r')
plt.show()

sns.pairplot(df)

sns.pairplot(df,hue='Position',corner=True,diag_kind='kde',plot_kws={'alpha':0.5,'s':80,'edgecolor':'k'})

